import { Injectable, signal } from '@angular/core';

export type Lang = 'fr' | 'ki';

export const TRANSLATIONS: Record<Lang, Record<string, string>> = {
  fr: {
    'nav.trips': 'Trajets', 'nav.propose': 'Proposer un trajet',
    'nav.messages': 'Messages', 'nav.profile': 'Mon profil',
    'nav.logout': 'Déconnexion', 'nav.login': 'Connexion',
    'nav.register': "S'inscrire", 'nav.dashboard': 'Tableau de bord',
    'nav.bookings': 'Demande de réservations', 'nav.notifications': 'Notifications',
    'nav.my-bookings': 'Mes réservations',
    'home.hero.title': 'Voyagez ensemble,', 'home.hero.accent': 'partagez les frais',
    'home.hero.subtitle': 'Trouvez un covoiturage pour votre prochain trajet ou proposez le vôtre.',
    'home.search.from': 'Départ', 'home.search.to': 'Arrivée', 'home.search.date': 'Date',
    'home.search.fromPlaceholder': 'Ville de départ', 'home.search.toPlaceholder': "Ville d'arrivée",
    'home.search.btn': 'Rechercher', 'home.why.title': 'Pourquoi ShareWay ?',
    'home.feature.economic': 'Économique', 'home.feature.economic.desc': 'Partagez les frais de carburant.',
    'home.feature.eco': 'Écologique', 'home.feature.eco.desc': "Moins de voitures sur la route.",
    'home.feature.friendly': 'Convivial', 'home.feature.friendly.desc': 'Faites de nouvelles rencontres.',
    'home.feature.safe': 'Sécurisé', 'home.feature.safe.desc': 'Profils vérifiés et avis.',
    'auth.login.title': 'Connexion', 'auth.login.subtitle': 'Bon retour parmi nous !',
    'auth.login.email': 'Email', 'auth.login.password': 'Mot de passe',
    'auth.login.submit': 'Se connecter', 'auth.login.loading': 'Connexion...',
    'auth.login.noAccount': "Pas encore de compte ?", 'auth.login.register': "S'inscrire",
    'auth.login.error': 'Identifiants incorrects',
    'auth.forgot.title': 'Mot de passe oublié',
    'auth.forgot.subtitle': 'Entrez votre email pour recevoir un lien de réinitialisation',
    'auth.forgot.email': 'Email', 'auth.forgot.submit': 'Envoyer le lien',
    'auth.forgot.success': 'Un email de réinitialisation vous a été envoyé !',
    'auth.forgot.back': 'Retour à la connexion',
    'auth.register.title': 'Créer un compte', 'auth.register.subtitle': 'Rejoignez ShareWay',
    'auth.register.firstName': 'Prénom', 'auth.register.lastName': 'Nom',
    'auth.register.phone': 'Téléphone', 'auth.register.password': 'Mot de passe',
    'auth.register.submit': 'Créer mon compte', 'auth.register.loading': 'Création...',
    'auth.register.hasAccount': 'Déjà un compte ?', 'auth.register.login': 'Se connecter',
    'auth.register.role': 'Je veux être',
    'auth.register.role.driver': 'Conducteur', 'auth.register.role.passenger': 'Passager',
    'auth.register.role.both': 'Les deux',
    'auth.required': 'Requis', 'auth.emailRequired': "L'email est requis",
    'auth.emailInvalid': 'Email invalide', 'auth.passwordMin': '8 caractères minimum',
    'trips.search.placeholder.from': 'Départ', 'trips.search.placeholder.to': 'Arrivée',
    'trips.search.seats': 'Places', 'trips.search.btn': 'Rechercher',
    'trips.filters': 'Filtres avancés', 'trips.filters.maxPrice': 'Prix max',
    'trips.filters.minRating': 'Note min', 'trips.filters.timeFrom': 'Départ après',
    'trips.filters.timeTo': 'Départ avant', 'trips.filters.music': 'Musique',
    'trips.filters.smoking': 'Fumeur', 'trips.filters.pets': 'Animaux',
    'trips.filters.reset': 'Réinitialiser', 'trips.filters.apply': 'Appliquer',
    'trips.loading': 'Recherche...', 'trips.empty.title': 'Aucun trajet trouvé',
    'trips.empty.desc': "Essayez d'autres dates ou villes", 'trips.empty.propose': 'Proposer ce trajet',
    'trips.count.singular': 'trajet trouvé', 'trips.count.plural': 'trajets trouvés',
    'trips.seat.singular': 'place', 'trips.seat.plural': 'places',
    'trips.create.title': 'Proposer un trajet', 'trips.create.subtitle': 'Partagez votre voiture',
    'trips.create.section.route': '📍 Itinéraire', 'trips.create.section.time': '🕐 Horaire',
    'trips.create.section.seats': '💺 Places & prix', 'trips.create.section.prefs': '🎵 Préférences',
    'trips.create.section.stops': '📌 Arrêts intermédiaires',
    'trips.create.section.recurrence': '🔁 Récurrence',
    'trips.create.depCity': 'Ville de départ *', 'trips.create.arrCity': "Ville d'arrivée *",
    'trips.create.depAddr': 'Adresse de départ', 'trips.create.arrAddr': "Adresse d'arrivée",
    'trips.create.depTime': 'Date et heure de départ *', 'trips.create.arrTime': "Heure d'arrivée estimée",
    'trips.create.seats': 'Nombre de places *', 'trips.create.price': 'Prix par passager *',
    'trips.create.currency': 'Devise', 'trips.create.submit': 'Publier le trajet',
    'trips.create.publishing': 'Publication...', 'trips.create.cancel': 'Annuler',
    'trips.create.addStop': '+ Ajouter un arrêt', 'trips.create.removeStop': 'Supprimer',
    'trips.create.isRecurring': 'Trajet récurrent',
    'trips.create.frequency': 'Fréquence',
    'trips.create.frequency.once': 'Une seule fois',
    'trips.create.frequency.weekly': 'Chaque semaine',
    'trips.create.frequency.biweekly': 'Toutes les 2 semaines',
    'trips.create.frequency.monthly': 'Chaque mois',
    'trips.create.recurringDays': 'Jours de la semaine',
    'trips.create.recurringEnd': 'Date de fin de récurrence',
    'trips.recurring': '🔁 Récurrent',
    'trips.prefs.music': '🎵 Musique', 'trips.prefs.smoking': '🚬 Fumeur autorisé',
    'trips.prefs.pets': '🐶 Animaux acceptés', 'trips.prefs.talking': '💬 Bavardage',
    'trips.prefs.ac': '❄️ Climatisation',
    'trips.prefs.largeLuggage': '🧳 Bagage large accepté',
    'trips.prefs.smallLuggage': '🎒 Petite bagage accepté',
    'messages.title': 'Messages', 'messages.empty': 'Aucune conversation',
    'messages.selectConv': 'Sélectionnez une conversation',
    'messages.inputPlaceholder': 'Écrivez un message...', 'messages.send': 'Envoyer',
    'messages.loading': 'Chargement...', 'messages.read': 'Lu',
    'profile.memberSince': 'Membre depuis', 'profile.trips': 'Trajets proposés',
    'profile.reviews': 'Avis', 'profile.edit': 'Modifier le profil',
    'profile.save': 'Enregistrer', 'profile.cancel': 'Annuler',
    'profile.bio': 'Bio', 'profile.bioPlaceholder': 'Parlez-vous de vous...',
    'profile.phone': 'Téléphone', 'profile.phoneVisible': 'Numéro visible publiquement',
    'profile.preferences': 'Préférences de voyage',
    'profile.vehicle': 'Mon véhicule', 'profile.vehicle.brand': 'Marque',
    'profile.vehicle.model': 'Modèle', 'profile.vehicle.color': 'Couleur',
    'profile.vehicle.plate': 'Plaque d\'immatriculation', 'profile.vehicle.year': 'Année',
    'profile.vehicle.save': 'Enregistrer le véhicule',
    'profile.identity': 'Vérification d\'identité',
    'profile.identity.upload': 'Télécharger une pièce d\'identité',
    'profile.identity.verified': '✅ Identité vérifiée', 'profile.identity.pending': '⏳ En attente',
    'profile.role': 'Mon rôle', 'profile.role.switch': 'Changer de rôle',
    'profile.role.driver': 'Conducteur', 'profile.role.passenger': 'Passager',
    'profile.role.both': 'Les deux',
    'profile.lang': 'Langue préférée',
    'profile.bookings': 'Mes réservations',
    'dashboard.title': 'Tableau de bord conducteur',
    'dashboard.earnings': 'Revenus totaux', 'dashboard.trips': 'Trajets effectués',
    'dashboard.passengers': 'Passagers transportés', 'dashboard.rating': 'Note moyenne',
    'dashboard.completion': 'Taux de complétion', 'dashboard.upcoming': 'Trajets à venir',
    'dashboard.chart': 'Revenus par mois', 'dashboard.myTrips': 'Mes trajets proposés',
    'bookings.title': 'Mes réservations', 'bookings.empty': 'Aucune réservation',
    'bookings.cancel': 'Annuler la réservation', 'bookings.status.confirmed': 'Confirmée',
    'bookings.status.cancelled': 'Annulée', 'bookings.leaveReason': 'Raison de l\'annulation',
    'bookings.status.completed': 'Terminée',
    'bookings.leaveReason.placeholder': 'Expliquez votre annulation au conducteur...',
    'bookings.notifyDriver': 'Notifier le conducteur',
    'review.title': 'Laisser un avis', 'review.comment': 'Commentaire (optionnel)',
    'review.comment.placeholder': 'Décrivez votre expérience...',
    'review.submit': 'Publier l\'avis', 'review.thanks': 'Merci pour votre avis !',
    'cancel.trip.title': 'Annuler le trajet',
    'cancel.trip.reason': 'Message aux passagers *',
    'cancel.trip.reason.placeholder': 'Expliquez la raison de l\'annulation...',
    'cancel.trip.notify': 'Envoyer un message aux passagers',
    'cancel.trip.confirm': 'Confirmer l\'annulation',
    'cancel.booking.title': 'Annuler ma réservation',
    'cancel.booking.reason': 'Message au conducteur',
    'cancel.booking.confirm': 'Confirmer l\'annulation',
    'share.title': 'Partager ce trajet', 'share.copy': 'Copier le lien',
    'share.copied': 'Lien copié !', 'share.whatsapp': 'WhatsApp', 'share.sms': 'SMS',
    'notifications.title': 'Notifications', 'notifications.empty': 'Aucune notification',
    'notifications.markRead': 'Tout marquer comme lu',
    'trip.arrival': 'Arrivée', 'trip.description': 'Description du trajet',
    'trip.passengers': 'Passagers', 'trip.noPassengers': 'Aucun passager',
    'trip.perPerson': 'par personne', 'trip.available': 'Place(s) disponible(s)',
    'trip.loginToBook': 'Se connecter pour réserver',
    'trip.ownTrip': 'C\'est votre trajet', 'trip.cancel': 'Annuler le trajet',
    'trip.joined': 'Vous êtes inscrit', 'trip.leave': 'Annuler ma réservation',
    'trip.book': 'Réserver une place', 'trip.full': 'Complet',
    'trip.driver': 'Conducteur', 'trip.contact': 'Contacter',
    'trip.bookSuccess': 'Réservation confirmée !', 'trip.leaveSuccess': 'Réservation annulée.',
    'trip.complete': 'Marquer comme terminé', 'trip.share': 'Partager',
    'trip.stops': 'Arrêts intermédiaires', 'trip.vehicle': 'Véhicule',
    'trip.passengers.list': 'Liste des passagers', 'trip.passengers.contact': 'Contact',
    'trip.review': 'Laisser un avis',
    'trip.currency': 'Devise de paiement',
    'trip.noDriver': 'Conducteurs uniquement',
    'footer.copyright': '© ShareWay. Tous droits réservés.',
    'footer.about': 'À propos', 'footer.contact': 'Contact',
    'footer.terms': "Conditions d'utilisation", 'footer.privacy': 'Confidentialité',
    'ad.title': 'Publicité', 'ad.sponsored': 'Sponsorisé',
    'days.MON': 'Lun', 'days.TUE': 'Mar', 'days.WED': 'Mer', 'days.THU': 'Jeu',
    'days.FRI': 'Ven', 'days.SAT': 'Sam', 'days.SUN': 'Dim',
    'contact.title': 'Contactez-nous', 'contact.subtitle': 'Une question ? Une suggestion ? N\'hésitez pas à nous écrire.',
    'contact.name': 'Nom complet', 'contact.name.placeholder': 'Votre nom',
    'contact.email': 'Email', 'contact.email.placeholder': 'Votre email',
    'contact.subject': 'Sujet', 'contact.subject.placeholder': 'Sujet de votre message',
    'contact.message': 'Message', 'contact.message.placeholder': 'Décrivez votre demande...',
    'contact.submit': 'Envoyer le message', 'contact.sending': 'Envoi en cours...',
    'contact.success': 'Votre message a été envoyé avec succès !',
    'contact.info.title': 'Nos coordonnées', 'contact.info.email': 'Email', 'contact.info.phone': 'Téléphone',
    'faq.title': 'Questions fréquentes', 'faq.subtitle': 'Trouvez rapidement les réponses à vos questions',
    'faq.q1': 'Qu\'est-ce que ShareWay ?', 'faq.a1': 'ShareWay est une plateforme de covoiturage qui connecte conducteurs et passagers souhaitant voyager ensemble. Vous pouvez proposer un trajet ou réserver une place existante pour partager les frais de carburant.',
    'faq.q2': 'Comment créer un trajet ?', 'faq.a2': 'Connectez-vous à votre compte, cliquez sur "Proposer un trajet" et remplissez les informations : ville de départ, destination, date, heure, nombre de places et prix. Vous pouvez aussi ajouter des arrêts intermédiaires et des préférences.',
    'faq.q3': 'Comment réserver une place ?', 'faq.a3': 'Recherchez un trajet qui correspond à votre itinéraire, vérifiez les détails et cliquez sur "Réserver une place". Vous recevrez une confirmation par notification une fois le conducteur votre demande acceptée.',
    'faq.q4': 'Comment fonctionne le paiement ?', 'faq.a4': 'Le paiement se fait directement entre passager et conducteur, en espèces ou par mobile money. ShareWay ne prend pas de commission, le prix est fixé par le conducteur et correspond au partage des frais de carburant.',
    'faq.q5': 'Comment annuler un trajet ou une réservation ?', 'faq.a5': 'Vous pouvez annuler votre réservation depuis votre espace "Mes réservations". Si vous êtes conducteur et devez annuler un trajet, les passagers inscrits seront automatiquement notifiés par message.',
    'faq.q6': 'Comment est assurée ma sécurité ?', 'faq.a6': 'Tous les profils sont vérifiés et vous pouvez consulter les avis d\'autres utilisateurs avant de réserver. Nous vous recommandons de toujours vérifier le véhicule et de partager votre itinéraire avec un proche.',
    'admin.ads': 'Publicités', 'admin.ads.manage': 'Gérer les publicités',
    'admin.roleRequests.title': 'Demandes de rôle',
    'admin.roleRequests.subtitle': 'demandes en attente',
    'admin.roleRequests.empty': 'Aucune demande de rôle.',
    'admin.roleRequests.filter.all': 'Toutes',
    'admin.roleRequests.filter.pending': 'En attente',
    'admin.roleRequests.filter.approved': 'Approuvées',
    'admin.roleRequests.filter.rejected': 'Rejetées',
    'admin.roleRequests.col.user': 'Utilisateur',
    'admin.roleRequests.col.currentRole': 'Rôle actuel',
    'admin.roleRequests.col.requestedRole': 'Rôle demandé',
    'admin.roleRequests.col.date': 'Date',
    'admin.roleRequests.col.status': 'Statut',
    'admin.roleRequests.col.actions': 'Actions',
    'admin.roleRequests.approve': 'Approuver',
    'admin.roleRequests.reject': 'Rejeter',
    'admin.roleRequests.next': 'Suivant',
    'admin.roleRequests.status.pending': 'En attente',
    'admin.roleRequests.status.approved': 'Approuvé',
    'admin.roleRequests.status.rejected': 'Rejeté',
    'common.loading': 'Chargement...', 'common.error': 'Une erreur est survenue',
    'common.save': 'Enregistrer', 'common.cancel': 'Annuler', 'common.confirm': 'Confirmer',
    'common.delete': 'Supprimer', 'common.edit': 'Modifier', 'common.back': '← Retour',
    'common.close': 'Fermer', 'common.yes': 'Oui', 'common.no': 'Non',
    'cookies.title': 'Gestion des cookies',
    'cookies.message': 'Nous utilisons des cookies pour améliorer votre expérience, analyser le trafic et personnaliser le contenu. Vous pouvez choisir les catégories de cookies que vous acceptez.',
    'cookies.learn_more': 'En savoir plus',
    'cookies.change_anytime': 'Vous pouvez modifier vos préférences à tout moment depuis votre tableau de bord.',
    'cookies.reject_all': 'Tout refuser',
    'cookies.accept_selection': 'Accepter la sélection',
    'cookies.accept_all': 'Tout accepter',
    'cookies.accept': 'Accepter',
    'cookies.reject': 'Refuser',

  },
  ki: {
    'nav.trips': 'Inzira', 'nav.propose': 'Tegura inzira',
    'nav.messages': 'Ubutumwa', 'nav.profile': 'Umwirondoro wanje',
    'nav.logout': 'Sohoka', 'nav.login': 'Injira', 'nav.register': 'Iyandikishe',
    'nav.dashboard': 'Imbonerahamwe', 'nav.bookings': 'Ingendo nemeje',
    'nav.notifications': 'Amakuru',
    'home.hero.title': 'Gutwara hamwe,', 'home.hero.accent': 'mugabane amafaranga',
    'home.hero.subtitle': 'Rondera gutwara hamwe canke tegura inzira yawe.',
    'home.search.from': 'Aratangira', 'home.search.to': 'Agasozera', 'home.search.date': 'Itariki',
    'home.search.fromPlaceholder': 'Igisagara aho utangura',
    'home.search.toPlaceholder': 'Igisagara agasozera',
    'home.search.btn': 'Rondera', 'home.why.title': 'Kubera iki ShareWay?',
    'home.feature.economic': 'Inexpensive', 'home.feature.economic.desc': 'Mugabane amafuta.',
    'home.feature.eco': 'Ivyiza vya kamere', 'home.feature.eco.desc': 'Imodoka nke mu nzira.',
    'home.feature.friendly': 'Ubugenzi', 'home.feature.friendly.desc': 'Hari abantu mushobora guhurira.',
    'home.feature.safe': 'Abo kwizera', 'home.feature.safe.desc': 'Indangamuntu zisuzumwe.',
    'auth.login.title': 'Injira', 'auth.login.subtitle': 'Turakuzabye!',
    'auth.login.email': 'Imeyili', 'auth.login.password': 'Ijambobanga',
    'auth.login.submit': 'Injira', 'auth.login.loading': 'Tegereza...',
    'auth.login.noAccount': 'Nta konti ufise?', 'auth.login.register': 'Iyandikishe',
    'auth.login.error': 'Amakuru si yo',
    'auth.forgot.title': 'Ijambobanga ryabuze',
    'auth.forgot.subtitle': 'Injira imeyili yawe kugira umeze ubwishyu',
    'auth.forgot.email': 'Imeyili', 'auth.forgot.submit': 'Tuma ubwishyu',
    'auth.forgot.success': 'Imeyili yo kugarura ijambobomba yaratumirwe!',
    'auth.forgot.back': 'Subira kwinjira',
    'auth.register.title': 'Fungura konti', 'auth.register.subtitle': 'Injira mu muryango wa ShareWay',
    'auth.register.firstName': 'Izina ribanza', 'auth.register.lastName': "Izina ry'umuryango",
    'auth.register.phone': 'Telefone', 'auth.register.password': 'Ijambobanga',
    'auth.register.submit': 'Fungura konti yanje', 'auth.register.loading': 'Gutunganya...',
    'auth.register.hasAccount': 'Ufise konti kare?', 'auth.register.login': 'Injira',
    'auth.register.role': 'Ndashaka kuba',
    'auth.register.role.driver': 'Umushoferi', 'auth.register.role.passenger': 'Umugendyi',
    'auth.register.role.both': 'Ivyompi',
    'auth.required': 'Birakenewe', 'auth.emailRequired': 'Imeyili irakenewe',
    'auth.emailInvalid': 'Imeyili si yo', 'auth.passwordMin': 'Inyuguti 8 nibura',
    'trips.search.placeholder.from': 'Aratangira', 'trips.search.placeholder.to': 'Agasozera',
    'trips.search.seats': 'Intebe', 'trips.search.btn': 'Rondera',
    'trips.filters': 'Gushaka birambuye', 'trips.filters.maxPrice': 'Igiciro ntarengwa',
    'trips.filters.minRating': 'Amanota ashaka', 'trips.filters.timeFrom': 'Gutangura nyuma ya',
    'trips.filters.timeTo': 'Gutangura imbere ya', 'trips.filters.music': 'Indirimbo',
    'trips.filters.smoking': 'Kunywa itabi', 'trips.filters.pets': 'Amatungo',
    'trips.filters.reset': 'Subira inyuma', 'trips.filters.apply': 'Shira mu ngiro',
    'trips.loading': 'Inzira ziraronderwa...', 'trips.empty.title': 'Nta nzira ibonetse',
    'trips.empty.desc': 'Gerageza itariki canke ibisagara bindi',
    'trips.empty.propose': 'Tegura iyi nzira',
    'trips.count.singular': 'inzira ibonetse', 'trips.count.plural': 'inzira zibonetse',
    'trips.seat.singular': 'intebe', 'trips.seat.plural': 'intebe',
    'trips.create.title': 'Tegura inzira', 'trips.create.subtitle': 'Gabana imodoka yawe',
    'trips.create.section.route': '📍 Inzira', 'trips.create.section.time': '🕐 Amasaha',
    'trips.create.section.seats': '💺 Intebe & igiciro',
    'trips.create.section.prefs': '🎵 Ibifuzo',
    'trips.create.section.stops': '📌 Ibibararo vya hagati',
    'trips.create.section.recurrence': '🔁 Gusubiramo',
    'trips.create.depCity': 'Igisagara aho utangura *',
    'trips.create.arrCity': 'Igisagara agasozera *',
    'trips.create.depAddr': 'Aderesi yo gutangurira',
    'trips.create.arrAddr': 'Aderesi yo gusozera',
    'trips.create.depTime': 'Itariki n\'isaha yo gutangura *',
    'trips.create.arrTime': 'Isaha yo kugerako (iteganijwe)',
    'trips.create.seats': 'Umubare w\'intebe *',
    'trips.create.price': 'Igiciro ku musafuzi *',
    'trips.create.currency': 'Ifaranga',
    'trips.create.submit': 'Sohorana inzira', 'trips.create.publishing': 'Gutangaza...',
    'trips.create.cancel': 'Hagarika',
    'trips.create.addStop': '+ Ongeraho ikibararo', 'trips.create.removeStop': 'Akura',
    'trips.create.isRecurring': 'Inzira isubirwamo',
    'trips.create.frequency': 'Kangahe', 'trips.create.frequency.once': 'Rimwe gusa',
    'trips.create.frequency.weekly': 'Buri ndwi', 'trips.create.frequency.biweekly': 'Indwi ezviri',
    'trips.create.frequency.monthly': 'Buri kwezi',
    'trips.create.recurringDays': 'Imisi y\'indwi', 'trips.create.recurringEnd': 'Itariki yo guturikirira',
    'trips.recurring': '🔁 Isubirwamo',
    'trips.prefs.music': '🎵 Indirimbo', 'trips.prefs.smoking': '🚬 Itabi ryemerewe',
    'trips.prefs.pets': '🐶 Ibikoko biremewe', 'trips.prefs.talking': '💬 Kuganira',
    'trips.prefs.largeLuggage': '🧳 Valise niniya',
    'trips.prefs.smallLuggage': '🎒 Valise ntoya',
    'trips.prefs.ac': '❄️ Gukanyisha',
    'messages.title': 'Ubutumwa', 'messages.empty': 'Nta makumunigo ahari',
    'messages.selectConv': 'Hitamo makumunigo',
    'messages.inputPlaceholder': 'Andika ubutumwa...', 'messages.send': 'Tuma',
    'messages.loading': 'Biratunganywa...', 'messages.read': 'Basomye',
    'profile.memberSince': 'Umunyamuryango kuva', 'profile.trips': 'Inzira zateguwe',
    'profile.reviews': 'Ibitekerezo', 'profile.edit': 'Hindura umwirondoro',
    'profile.save': 'Bika', 'profile.cancel': 'Hagarika',
    'profile.bio': 'Ivyerekeye wewe', 'profile.bioPlaceholder': 'Wibwire...',
    'profile.phone': 'Telefone', 'profile.phoneVisible': 'Nimero iboneka',
    'profile.preferences': 'Ivyo ukunda mu rugendo',
    'profile.vehicle': 'Imodoka yanje', 'profile.vehicle.brand': 'Ubwoko',
    'profile.vehicle.model': 'Indangamuntu ya modoka', 'profile.vehicle.color': 'Akagara',
    'profile.vehicle.plate': 'Nimero ya plaki', 'profile.vehicle.year': 'Umwaka',
    'profile.vehicle.save': 'Bika imodoka',
    'profile.identity': 'Kwemeza indangamuntu',
    'profile.identity.upload': 'Shira indangamuntu',
    'profile.identity.verified': '✅ Vyemejwe', 'profile.identity.pending': '⏳ Birategerezwa',
    'profile.role': 'Inshingano yanje', 'profile.role.switch': 'Hindura inshingano',
    'profile.role.driver': 'Umushoferi', 'profile.role.passenger': 'Umugendyi',
    'profile.role.both': 'Ivyompi', 'profile.lang': 'Ururimi ukunda', 'profile.bookings': 'Ivyo nabitse',
    'dashboard.title': 'Imbonerahamwe y\'umushoferi',
    'dashboard.earnings': 'Amafaranga yose', 'dashboard.trips': 'Inzira zarangiye',
    'dashboard.passengers': 'Abagendyi batwaye', 'dashboard.rating': 'Amanota hagati',
    'dashboard.completion': 'Inzira zarangiye %', 'dashboard.upcoming': 'Inzira ziri imbere',
    'dashboard.chart': 'Amafaranga buri kwezi', 'dashboard.myTrips': 'Inzira nateguriye',
    'bookings.title': 'Ingendo nemeje', 'bookings.empty': 'Nta rugendo narumwe wemeje',
    'bookings.cancel': 'Hagarika inyandiko', 'bookings.status.confirmed': 'Yemejwe',
    'bookings.status.cancelled': 'Rwasibijwe', 'bookings.leaveReason': 'Impamvu rwasibijwe',
    'bookings.status.completed': 'Rwarangiye',
    'bookings.leaveReason.placeholder': 'Tanga impamvu kumushoferi...',
    'bookings.notifyDriver': 'Menyesha umushoferi',
    'review.title': 'Tanga ibitekerezo', 'review.comment': 'Igitekerezo (si ngombwa)',
    'review.comment.placeholder': 'Vuga ivyabaye mu rugendo...',
    'review.submit': 'Sohorana ibitekerezo', 'review.thanks': 'Murakoze cane!',
    'cancel.trip.title': 'Hagarika urugendo',
    'cancel.trip.reason': 'Ubutumwa ku bagendyi *',
    'cancel.trip.reason.placeholder': 'Tanga impamvu y\'uguhagarika...',
    'cancel.trip.notify': 'Tumira ubutumwa abagendyi',
    'cancel.trip.confirm': 'Emeza guhagarika',
    'cancel.booking.title': 'Hagarika inyandiko yanje',
    'cancel.booking.reason': 'Ubutumwa kumushoferi',
    'cancel.booking.confirm': 'Emeza guhagarika',
    'share.title': 'Sangira uru rugendo', 'share.copy': 'Kopa urunigi',
    'share.copied': 'Urunigi rwakopiwe!', 'share.whatsapp': 'WhatsApp', 'share.sms': 'SMS',
    'notifications.title': 'Amakuru', 'notifications.empty': 'Nta makuru ahari',
    'notifications.markRead': 'Sema vyose nk\'ibisomwe',
    'trip.arrival': 'Agasozera', 'trip.description': 'Idonido ry\'urugendo',
    'trip.passengers': 'Ingenzi', 'trip.noPassengers': 'Nta ngezi ihari',
    'trip.perPerson': 'ku muntu', 'trip.available': 'Ibibanza bisigaye',
    'trip.loginToBook': 'Injira kugira ubone', 'trip.ownTrip': 'Iyi nzira ni iyawe',
    'trip.cancel': 'Hagarika inzira', 'trip.joined': 'Wanditse',
    'trip.leave': 'Hagarika inyandiko yanje', 'trip.book': 'Bona intebe',
    'trip.full': 'Ryuzuywe', 'trip.driver': 'Umushoferi', 'trip.contact': 'Muvugishe',
    'trip.bookSuccess': 'Wanditswe neza!', 'trip.leaveSuccess': 'Inyandiko irahanutse.',
    'trip.complete': 'Sema inzira irarangiye', 'trip.share': 'Sangira',
    'trip.stops': 'Ibibararo vya hagati', 'trip.vehicle': 'Imodoka',
    'trip.passengers.list': 'Urutonde rw\'abagendyi', 'trip.passengers.contact': 'Aho bagerwaho',
    'trip.review': 'Tanga ibitekerezo', 'trip.currency': 'Ifaranga ryo kwishura',
    'trip.noDriver': 'Abashofer gusa',
    'footer.copyright': '© ShareWay. Uburenganzira bwose burarindwa.',
    'footer.about': 'Ivyerekeye', 'footer.contact': 'Tuvugishe',
    'footer.terms': "Amategeko y'ikoreshwa", 'footer.privacy': 'Ubuzima bwite',
    'ad.title': 'Ikampeni', 'ad.sponsored': 'Iravuzwe',
    'days.MON': 'Kwa', 'days.TUE': 'Gat', 'days.WED': 'Gac', 'days.THU': 'Ka',
    'days.FRI': 'Gnu', 'days.SAT': 'Cya', 'days.SUN': 'Csu',
    'admin.ads': 'Ikampeni', 'admin.ads.manage': 'Gerer ikampeni',
    'admin.roleRequests.title': 'Ibisabwa vy\'inshingano',
    'admin.roleRequests.subtitle': 'ibisabwa birategerezwa',
    'admin.roleRequests.empty': 'Nta kintu kisabwa kirabonetse.',
    'admin.roleRequests.filter.all': 'Vyose',
    'admin.roleRequests.filter.pending': 'Birategerezwa',
    'admin.roleRequests.filter.approved': 'Vyemejwe',
    'admin.roleRequests.filter.rejected': 'Rwasibijwe',
    'admin.roleRequests.col.user': 'Umukoresha',
    'admin.roleRequests.col.currentRole': 'Inshingano zo kuri ubu',
    'admin.roleRequests.col.requestedRole': 'Inshingano yisabiye',
    'admin.roleRequests.col.date': 'Itariki',
    'admin.roleRequests.col.status': 'Imimerere',
    'admin.roleRequests.col.actions': 'Ibikorwa',
    'admin.roleRequests.approve': 'Emeza',
    'admin.roleRequests.reject': 'Anka',
    'admin.roleRequests.next': 'Imbere',
    'admin.roleRequests.status.pending': 'Birategerezwa',
    'admin.roleRequests.status.approved': 'Vyemejwe',
    'admin.roleRequests.status.rejected': 'Rwasibijwe',
    'contact.title': 'Tuvugishe', 'contact.subtitle': 'Ubufasha bushasha? Tuvugishe.',
    'contact.name': 'Izina', 'contact.name.placeholder': 'Izina ryawe',
    'contact.email': 'Imeyili', 'contact.email.placeholder': 'Imeyili yawe',
    'contact.subject': 'Inkopi', 'contact.subject.placeholder': 'Inkopi y\'ubutumwa bwawe',
    'contact.message': 'Ubutumwa', 'contact.message.placeholder': 'Andika ubutumwa bwawe...',
    'contact.submit': 'Tuma ubutumwa', 'contact.sending': 'Butumwa...',
    'contact.success': 'Ubutumwa bwawe bwarabonywe neza!',
    'contact.info.title': 'Aho turi', 'contact.info.email': 'Imeyili', 'contact.info.phone': 'Telefone',
    'faq.title': 'Ibibazo bisanzwe', 'faq.subtitle': 'Sangira ibibazo vyawe vyo kwibaza',
    'faq.q1': 'ShareWay ni iki?', 'faq.a1': 'ShareWay ni urubuga rwo gutwara hamwe ruhuza abashoferi n\'abagendyi bifuza gukora inzira hamwe. Ushobora kugaburira inzira canke kugura intebe y\'ubusabane kugira mugabane amafuta.',
    'faq.q2': 'Nigute ntangura inzira?', 'faq.a2': 'Injira mu konti yawe, kanda "Tegura inzira" uzuza amakuru: igisagara aho utangura, agasozera, itariki, isaha, umubare w\'intebe n\'igiciro.',
    'faq.q3': 'Nigute ngura intebe?', 'faq.a3': 'Rondera inzira ifitanye no ku nzira yawe, raba ibisobanuro kandi ukande "Gura intebe". Uzakira ubusobanuro bw\'emeza.',
    'faq.q4': 'Nigute ubwishyu bukora?', 'faq.a4': 'Ubwishyu bukora hagati y\'umugendyi n\'umushoferi, mu faranga canke mobile money. ShareWay nta komisio iranga, igiciro kiratangwa n\'umushoferi.',
    'faq.q5': 'Nigute nguhagarika inzira canke inyandiko?', 'faq.a5': 'Ushobora guhagarika inyandiko yawe ukurikije "Ivyo nabitse". Niba umushoferi ukeneye guhagarika inzira, abagendyi bazamenyerewe.',
    'faq.q6': 'Nigute ubwite bwange bukwiye?', 'faq.a6': 'Imbonerahamwe yose isuzumwe kandi ushobora kubona ibitekerezo vy\'abandi bakoresha mbere yo kugura intebe.',
    'common.loading': 'Biratunganywa...', 'common.error': 'Habaye ikosa',
    'common.save': 'Bika', 'common.cancel': 'Hagarika', 'common.confirm': 'Emeza',
    'common.delete': 'Siba', 'common.edit': 'Hindura', 'common.back': '← Subira',
    'common.close': 'Funga', 'common.yes': 'Ego', 'common.no': 'Oya',
    'cookies.title': 'Kugenzura amakuki',
    'cookies.message': 'Dukoresha amakuki (cookies) kugira ngo dutange serivisi nziza, dukurikire ubusanzwe bw\'urugendo, kandi dutegure amakuru y\'ingenyo. Urashobola guhitamo ubwoko bw\'amakuki wemera.',
    'cookies.learn_more': 'Menya byinshi',
    'cookies.change_anytime': 'Urashobola guhindura ubwisanzwe bwawe igihe cose ukoresheje ibibao byawe.',
    'cookies.reject_all': 'Anka vyose',
    'cookies.accept_selection': 'Emera ubwisanzwe',
    'cookies.accept_all': 'Emera vyose',
    'cookies.accept': 'Emera',
    'cookies.reject': 'Anka',
  }
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  private _lang = signal<Lang>((localStorage.getItem('sw_lang') as Lang) || 'fr');
  currentLang = this._lang.asReadonly();

  t(key: string): string {
    return TRANSLATIONS[this._lang()][key] ?? key;
  }

  setLang(lang: Lang): void {
    this._lang.set(lang);
    localStorage.setItem('sw_lang', lang);
  }

  toggle(): void { this.setLang(this._lang() === 'fr' ? 'ki' : 'fr'); }
}
