import { Currency } from './trip.model';

export const COUNTRY_CURRENCY_MAP: Record<string, Currency> = {
  'Burundi': 'FBU',
  'Bdi': 'FBU',

  'Rwanda': 'FRW',
  'Rwa': 'FRW',

  'France': 'EUR',
  'Allemagne': 'EUR', 'Germany': 'EUR',
  'Belgique': 'EUR', 'Belgium': 'EUR',
  'Pays-Bas': 'EUR', 'Netherlands': 'EUR',
  'Espagne': 'EUR', 'Spain': 'EUR',
  'Italie': 'EUR', 'Italy': 'EUR',
  'Portugal': 'EUR',
  'Grèce': 'EUR', 'Greece': 'EUR',
  'Autriche': 'EUR', 'Austria': 'EUR',
  'Irlande': 'EUR', 'Ireland': 'EUR',
  'Finlande': 'EUR', 'Finland': 'EUR',
  'Luxembourg': 'EUR',
  'Slovénie': 'EUR', 'Slovenia': 'EUR',
  'Slovaquie': 'EUR', 'Slovakia': 'EUR',
  'Estonie': 'EUR', 'Estonia': 'EUR',
  'Lettonie': 'EUR', 'Latvia': 'EUR',
  'Lituanie': 'EUR', 'Lithuania': 'EUR',
  'Malte': 'EUR', 'Malta': 'EUR',
  'Chypre': 'EUR', 'Cyprus': 'EUR',
  'Monaco': 'EUR', 'Andorre': 'EUR', 'Andorra': 'EUR',
  'Saint-Marin': 'EUR', 'San Marino': 'EUR',
  'Vatican': 'EUR',
  'Croatie': 'EUR', 'Croatia': 'EUR',
  'Bulgarie': 'EUR', 'Bulgaria': 'EUR',
  'Roumanie': 'EUR', 'Romania': 'EUR',
  'Pologne': 'EUR', 'Poland': 'EUR',
  'République tchèque': 'EUR', 'Czech Republic': 'EUR', 'Czechia': 'EUR',
  'Hongrie': 'EUR', 'Hungary': 'EUR',
  'Danemark': 'EUR', 'Denmark': 'EUR',
  'Suède': 'EUR', 'Sweden': 'EUR',
  'Norvège': 'EUR', 'Norway': 'EUR',
  'Suisse': 'EUR', 'Switzerland': 'EUR',
  'Islande': 'EUR', 'Iceland': 'EUR',
  'Lichtenstein': 'EUR',

  'États-Unis': 'USD', 'United States': 'USD',
  'Canada': 'USD',
  'Australie': 'USD', 'Australia': 'USD',
  'Nouvelle-Zélande': 'USD', 'New Zealand': 'USD',
  'Japon': 'USD', 'Japan': 'USD',
  'Chine': 'USD', 'China': 'USD',
  'Taïwan': 'USD', 'Taiwan': 'USD',
  'Corée du Sud': 'USD', 'South Korea': 'USD',
  'Singapour': 'USD', 'Singapore': 'USD',
  'Hong Kong': 'USD',
  'Philippines': 'USD',
  'Thaïlande': 'USD', 'Thailand': 'USD',
  'Vietnam': 'USD',
  'Malaisie': 'USD', 'Malaysia': 'USD',
  'Indonésie': 'USD', 'Indonesia': 'USD',
  'Inde': 'USD', 'India': 'USD',
  'Sri Lanka': 'USD',
  'Népal': 'USD', 'Nepal': 'USD',
  'Bangladesh': 'USD',
  'Pakistan': 'USD',
  'Cambodge': 'USD', 'Cambodia': 'USD',
  'Laos': 'USD',
  'Myanmar': 'USD', 'Birmanie': 'USD',
  'Mongolie': 'USD', 'Mongolia': 'USD',
  'Timor oriental': 'USD', 'East Timor': 'USD',

  'Nigeria': 'USD',
  'Kenya': 'USD',
  'Tanzanie': 'USD', 'Tanzania': 'USD',
  'République Démocratique du Congo': 'USD', 'Democratic Republic of the Congo': 'USD', 'RD Congo': 'USD', 'RDC': 'USD', 'Congo-Kinshasa': 'USD',
  'Congo': 'USD', 'République du Congo': 'USD', 'Congo-Brazzaville': 'USD', 'Congo Republic': 'USD',
  'Ouganda': 'USD', 'Uganda': 'USD',
  'Soudan': 'USD', 'Sudan': 'USD',
  'Soudan du Sud': 'USD', 'South Sudan': 'USD',
  'Égypte': 'USD', 'Egypt': 'USD',
  'Afrique du Sud': 'USD', 'South Africa': 'USD',
  'Sénégal': 'USD', 'Senegal': 'USD',
  'Cameroun': 'USD', 'Cameroon': 'USD',
  "Côte d'Ivoire": 'USD', 'Ivory Coast': 'USD',
  'Mali': 'USD',
  'Niger': 'USD',
  'Tchad': 'USD', 'Chad': 'USD',
  'Gabon': 'USD',
  'Guinée': 'USD', 'Guinea': 'USD',
  'Guinée équatoriale': 'USD', 'Equatorial Guinea': 'USD',
  'Bénin': 'USD', 'Benin': 'USD',
  'Togo': 'USD',
  'Sierra Leone': 'USD',
  'Liberia': 'USD',
  'Gambie': 'USD', 'Gambia': 'USD',
  'Guinée-Bissau': 'USD', 'Guinea-Bissau': 'USD',
  'Cap-Vert': 'USD', 'Cabo Verde': 'USD', 'Cape Verde': 'USD',
  'Burkina Faso': 'USD',
  'Madagascar': 'USD',
  'Mozambique': 'USD',
  'Angola': 'USD',
  'Zambie': 'USD', 'Zambia': 'USD',
  'Zimbabwe': 'USD',
  'Botswana': 'USD',
  'Namibie': 'USD', 'Namibia': 'USD',
  'Lesotho': 'USD',
  'Eswatini': 'USD', 'Swaziland': 'USD',
  'Malawi': 'USD',
  'Maurice': 'USD', 'Mauritius': 'USD',
  'Seychelles': 'USD',
  'Comores': 'USD', 'Comoros': 'USD',
  'Djibouti': 'USD',
  'Érythrée': 'USD', 'Eritrea': 'USD',
  'Somalie': 'USD', 'Somalia': 'USD',
  'Éthiopie': 'USD', 'Ethiopia': 'USD',
  'Libye': 'USD', 'Libya': 'USD',
  'Tunisie': 'USD', 'Tunisia': 'USD',
  'Maroc': 'USD', 'Morocco': 'USD',
  'Algérie': 'USD', 'Algeria': 'USD',
  'Mauritanie': 'USD', 'Mauritania': 'USD',
  'Îles Comores': 'USD',
  'São Tomé and Príncipe': 'USD', 'Sao Tomé and Príncipe': 'USD',
  'République centrafricaine': 'USD', 'Central African Republic': 'USD',

  'Brésil': 'USD', 'Brazil': 'USD',
  'Mexique': 'USD', 'Mexico': 'USD',
  'Argentine': 'USD', 'Argentina': 'USD',
  'Chili': 'USD', 'Chile': 'USD',
  'Colombie': 'USD', 'Colombia': 'USD',
  'Pérou': 'USD', 'Peru': 'USD',
  'Venezuela': 'USD',
  'Équateur': 'USD', 'Ecuador': 'USD',
  'Bolivie': 'USD', 'Bolivia': 'USD',
  'Paraguay': 'USD',
  'Uruguay': 'USD',
  'Guatemala': 'USD',
  'Honduras': 'USD',
  'Salvador': 'USD', 'El Salvador': 'USD',
  'Nicaragua': 'USD',
  'Costa Rica': 'USD',
  'Panama': 'USD',
  'Cuba': 'USD',
  'Haïti': 'USD', 'Haiti': 'USD',
  'République dominicaine': 'USD', 'Dominican Republic': 'USD',
  'Jamaïque': 'USD', 'Jamaica': 'USD',
  'Trinidad et Tobago': 'USD', 'Trinidad and Tobago': 'USD',
  'Guyana': 'USD',
  'Suriname': 'USD',
  'Belize': 'USD',

  'Arabie saoudite': 'USD', 'Saudi Arabia': 'USD',
  'Émirats arabes unis': 'USD', 'United Arab Emirates': 'USD',
  'Qatar': 'USD',
  'Koweït': 'USD', 'Kuwait': 'USD',
  'Bahreïn': 'USD', 'Bahrain': 'USD',
  'Oman': 'USD',
  'Jordanie': 'USD', 'Jordan': 'USD',
  'Liban': 'USD', 'Lebanon': 'USD',
  'Irak': 'USD', 'Iraq': 'USD',
  'Iran': 'USD',
  'Syrie': 'USD', 'Syria': 'USD',
  'Yémen': 'USD', 'Yemen': 'USD',
  'Israël': 'USD', 'Israel': 'USD',
  'Palestine': 'USD',
  'Turquie': 'USD', 'Turkey': 'USD',
  'Azerbaïdjan': 'USD', 'Azerbaijan': 'USD',
  'Géorgie': 'USD', 'Georgia': 'USD',
  'Arménie': 'USD', 'Armenia': 'USD',
  'Kazakhstan': 'USD',
  'Ouzbékistan': 'USD', 'Uzbekistan': 'USD',
  'Turkménistan': 'USD', 'Turkmenistan': 'USD',
  'Tadjikistan': 'USD', 'Tajikistan': 'USD',
  'Kirghizistan': 'USD', 'Kyrgyzstan': 'USD',
  'Afghanistan': 'USD',

  'Russie': 'USD', 'Russia': 'USD',
  'Ukraine': 'USD',
  'Biélorussie': 'USD', 'Belarus': 'USD',
  'Moldavie': 'USD', 'Moldova': 'USD',
  'Serbie': 'USD', 'Serbia': 'USD',
  'Monténégro': 'USD', 'Montenegro': 'USD',
  'Bosnie-Herzégovine': 'USD', 'Bosnia and Herzegovina': 'USD',
  'Macédoine du Nord': 'USD', 'North Macedonia': 'USD',
  'Albanie': 'USD', 'Albania': 'USD',
  'Kosovo': 'USD',
};

export function getCurrencyByCountry(country: string): Currency {
  if (!country) return 'FBU';
  const trimmed = country.trim();
  if (COUNTRY_CURRENCY_MAP[trimmed]) return COUNTRY_CURRENCY_MAP[trimmed];
  const lower = trimmed.toLowerCase();
  const match = Object.keys(COUNTRY_CURRENCY_MAP).find(k => k.toLowerCase() === lower);
  return match ? COUNTRY_CURRENCY_MAP[match] : 'FBU';
}
